### ISSUE TITLE
log file identifiers

### ISSUE THREAD

**Issue by laszewsk** [mlcommons/science#53]
make sure all log files have the following included

      * submission_benchmark
      * submission_org
      * submission_division
      * submissiom_version
      * submission_github_commit_version
      * submission_status
      * submission_platform

I suggest to have not version: but

```
submission:
  benchmark: earthquake
  org: University of Virginia
  submitter: Gregor von Laszewski
  email: tbd@email.com
  division: closed
  version: mlcommons-earthquake-v1.0
  github_commit_version: 954fb4772feef5c356b7cdf37f61fa65e11715ed
  status: completed
  platform: rivanna
```

In all yaml files so that the submission log entries can be created from them
